version: '3.1'

services:

  # This is the container for the web gui.
  ontoloci-web:
    image: ontoloci-web
    build:
      context: ../ontoloci-web
      dockerfile: Dockerfile
    ports:
      - 80:3000
    stdin_open: true # Needed to keep the image alive.